/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ExamSelectRouteImport } from './routes/exam-select'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedEncourageRouteImport } from './routes/_authenticated/encourage'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedCommunitiesRouteImport } from './routes/_authenticated/communities'
import { Route as AuthenticatedCirclesRouteImport } from './routes/_authenticated/circles'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedCommunitiesIndexRouteImport } from './routes/_authenticated/communities.index'
import { Route as AuthenticatedCirclesIndexRouteImport } from './routes/_authenticated/circles.index'
import { Route as AuthenticatedCommunitiesSlugRouteImport } from './routes/_authenticated/communities.$slug'
import { Route as AuthenticatedCirclesSlugRouteImport } from './routes/_authenticated/circles.$slug'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSelectRoute = ExamSelectRouteImport.update({
  id: '/exam-select',
  path: '/exam-select',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEncourageRoute = AuthenticatedEncourageRouteImport.update({
  id: '/encourage',
  path: '/encourage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunitiesRoute =
  AuthenticatedCommunitiesRouteImport.update({
    id: '/communities',
    path: '/communities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCirclesRoute = AuthenticatedCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunitiesIndexRoute =
  AuthenticatedCommunitiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCommunitiesRoute,
  } as any)
const AuthenticatedCirclesIndexRoute =
  AuthenticatedCirclesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCirclesRoute,
  } as any)
const AuthenticatedCommunitiesSlugRoute =
  AuthenticatedCommunitiesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCommunitiesRoute,
  } as any)
const AuthenticatedCirclesSlugRoute =
  AuthenticatedCirclesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCirclesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exam-select': typeof ExamSelectRoute
  '/onboarding': typeof OnboardingRoute
  '/trust': typeof TrustRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/circles': typeof AuthenticatedCirclesRouteWithChildren
  '/communities': typeof AuthenticatedCommunitiesRouteWithChildren
  '/create': typeof AuthenticatedCreateRoute
  '/encourage': typeof AuthenticatedEncourageRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/circles/$slug': typeof AuthenticatedCirclesSlugRoute
  '/communities/$slug': typeof AuthenticatedCommunitiesSlugRoute
  '/circles/': typeof AuthenticatedCirclesIndexRoute
  '/communities/': typeof AuthenticatedCommunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exam-select': typeof ExamSelectRoute
  '/onboarding': typeof OnboardingRoute
  '/trust': typeof TrustRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/create': typeof AuthenticatedCreateRoute
  '/encourage': typeof AuthenticatedEncourageRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/circles/$slug': typeof AuthenticatedCirclesSlugRoute
  '/communities/$slug': typeof AuthenticatedCommunitiesSlugRoute
  '/circles': typeof AuthenticatedCirclesIndexRoute
  '/communities': typeof AuthenticatedCommunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/exam-select': typeof ExamSelectRoute
  '/onboarding': typeof OnboardingRoute
  '/trust': typeof TrustRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRoute
  '/_authenticated/circles': typeof AuthenticatedCirclesRouteWithChildren
  '/_authenticated/communities': typeof AuthenticatedCommunitiesRouteWithChildren
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/encourage': typeof AuthenticatedEncourageRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/circles/$slug': typeof AuthenticatedCirclesSlugRoute
  '/_authenticated/communities/$slug': typeof AuthenticatedCommunitiesSlugRoute
  '/_authenticated/circles/': typeof AuthenticatedCirclesIndexRoute
  '/_authenticated/communities/': typeof AuthenticatedCommunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/exam-select'
    | '/onboarding'
    | '/trust'
    | '/check-in'
    | '/circles'
    | '/communities'
    | '/create'
    | '/encourage'
    | '/home'
    | '/profile'
    | '/circles/$slug'
    | '/communities/$slug'
    | '/circles/'
    | '/communities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/exam-select'
    | '/onboarding'
    | '/trust'
    | '/check-in'
    | '/create'
    | '/encourage'
    | '/home'
    | '/profile'
    | '/circles/$slug'
    | '/communities/$slug'
    | '/circles'
    | '/communities'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/exam-select'
    | '/onboarding'
    | '/trust'
    | '/_authenticated/check-in'
    | '/_authenticated/circles'
    | '/_authenticated/communities'
    | '/_authenticated/create'
    | '/_authenticated/encourage'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/circles/$slug'
    | '/_authenticated/communities/$slug'
    | '/_authenticated/circles/'
    | '/_authenticated/communities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExamSelectRoute: typeof ExamSelectRoute
  OnboardingRoute: typeof OnboardingRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-select': {
      id: '/exam-select'
      path: '/exam-select'
      fullPath: '/exam-select'
      preLoaderRoute: typeof ExamSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encourage': {
      id: '/_authenticated/encourage'
      path: '/encourage'
      fullPath: '/encourage'
      preLoaderRoute: typeof AuthenticatedEncourageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities': {
      id: '/_authenticated/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AuthenticatedCommunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circles': {
      id: '/_authenticated/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AuthenticatedCirclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities/': {
      id: '/_authenticated/communities/'
      path: '/'
      fullPath: '/communities/'
      preLoaderRoute: typeof AuthenticatedCommunitiesIndexRouteImport
      parentRoute: typeof AuthenticatedCommunitiesRoute
    }
    '/_authenticated/circles/': {
      id: '/_authenticated/circles/'
      path: '/'
      fullPath: '/circles/'
      preLoaderRoute: typeof AuthenticatedCirclesIndexRouteImport
      parentRoute: typeof AuthenticatedCirclesRoute
    }
    '/_authenticated/communities/$slug': {
      id: '/_authenticated/communities/$slug'
      path: '/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof AuthenticatedCommunitiesSlugRouteImport
      parentRoute: typeof AuthenticatedCommunitiesRoute
    }
    '/_authenticated/circles/$slug': {
      id: '/_authenticated/circles/$slug'
      path: '/$slug'
      fullPath: '/circles/$slug'
      preLoaderRoute: typeof AuthenticatedCirclesSlugRouteImport
      parentRoute: typeof AuthenticatedCirclesRoute
    }
  }
}

interface AuthenticatedCirclesRouteChildren {
  AuthenticatedCirclesSlugRoute: typeof AuthenticatedCirclesSlugRoute
  AuthenticatedCirclesIndexRoute: typeof AuthenticatedCirclesIndexRoute
}

const AuthenticatedCirclesRouteChildren: AuthenticatedCirclesRouteChildren = {
  AuthenticatedCirclesSlugRoute: AuthenticatedCirclesSlugRoute,
  AuthenticatedCirclesIndexRoute: AuthenticatedCirclesIndexRoute,
}

const AuthenticatedCirclesRouteWithChildren =
  AuthenticatedCirclesRoute._addFileChildren(AuthenticatedCirclesRouteChildren)

interface AuthenticatedCommunitiesRouteChildren {
  AuthenticatedCommunitiesSlugRoute: typeof AuthenticatedCommunitiesSlugRoute
  AuthenticatedCommunitiesIndexRoute: typeof AuthenticatedCommunitiesIndexRoute
}

const AuthenticatedCommunitiesRouteChildren: AuthenticatedCommunitiesRouteChildren =
  {
    AuthenticatedCommunitiesSlugRoute: AuthenticatedCommunitiesSlugRoute,
    AuthenticatedCommunitiesIndexRoute: AuthenticatedCommunitiesIndexRoute,
  }

const AuthenticatedCommunitiesRouteWithChildren =
  AuthenticatedCommunitiesRoute._addFileChildren(
    AuthenticatedCommunitiesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRoute
  AuthenticatedCirclesRoute: typeof AuthenticatedCirclesRouteWithChildren
  AuthenticatedCommunitiesRoute: typeof AuthenticatedCommunitiesRouteWithChildren
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedEncourageRoute: typeof AuthenticatedEncourageRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckInRoute: AuthenticatedCheckInRoute,
  AuthenticatedCirclesRoute: AuthenticatedCirclesRouteWithChildren,
  AuthenticatedCommunitiesRoute: AuthenticatedCommunitiesRouteWithChildren,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedEncourageRoute: AuthenticatedEncourageRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExamSelectRoute: ExamSelectRoute,
  OnboardingRoute: OnboardingRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
